[package]
name = "long-shell"
version = "0.1.0"
edition = "2024"
license = "MIT"
description = "A persistent, long-lived shell session manager with async real-time output streaming, callback hooks, and cross-platform encoding support."
repository = "https://github.com/ZEROLINGG/long-shell"
documentation = "https://docs.rs/long-shell"
homepage = "https://github.com/ZEROLINGG"

[dependencies]
anyhow = "1"
tokio = { version = "1", features = ["process", "io-util", "sync", "rt", "time", "macros"] }
serde = { version = "1", features = ["derive"] }

encoding_rs = "0.8"

[target.'cfg(windows)'.dependencies]
codepage = "0.1"